import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import UseStateEffectTimer from "@/components/UseStateEffectTimer";
import UseStateString from "@/components/UseStateString";
import { Box, Center, Flex, Text } from "@chakra-ui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Flex
          // justifyContent="center"
          alignItems="center"
          flexDirection="column"
        >
          <Text fontWeight={800}>useStateEffect Timer</Text>  
          <UseStateEffectTimer/>
          <Text fontWeight={800}>useState String</Text>  
          <UseStateString/>
        </Flex>
      </div>
    </>
  );
}
